# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: buzzer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='buzzer.proto',
  package='cabane.io',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0c\x62uzzer.proto\x12\tcabane.io\"\x1b\n\tBuzzQuery\x12\x0e\n\x06number\x18\x01 \x01(\x03\"\x1e\n\x0c\x42uzzResponse\x12\x0e\n\x06isBuzz\x18\x01 \x01(\x08\x32<\n\x04\x42uzz\x12\x34\n\x03\x41sk\x12\x14.cabane.io.BuzzQuery\x1a\x17.cabane.io.BuzzResponseb\x06proto3')
)




_BUZZQUERY = _descriptor.Descriptor(
  name='BuzzQuery',
  full_name='cabane.io.BuzzQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='cabane.io.BuzzQuery.number', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=54,
)


_BUZZRESPONSE = _descriptor.Descriptor(
  name='BuzzResponse',
  full_name='cabane.io.BuzzResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='isBuzz', full_name='cabane.io.BuzzResponse.isBuzz', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=86,
)

DESCRIPTOR.message_types_by_name['BuzzQuery'] = _BUZZQUERY
DESCRIPTOR.message_types_by_name['BuzzResponse'] = _BUZZRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BuzzQuery = _reflection.GeneratedProtocolMessageType('BuzzQuery', (_message.Message,), dict(
  DESCRIPTOR = _BUZZQUERY,
  __module__ = 'buzzer_pb2'
  # @@protoc_insertion_point(class_scope:cabane.io.BuzzQuery)
  ))
_sym_db.RegisterMessage(BuzzQuery)

BuzzResponse = _reflection.GeneratedProtocolMessageType('BuzzResponse', (_message.Message,), dict(
  DESCRIPTOR = _BUZZRESPONSE,
  __module__ = 'buzzer_pb2'
  # @@protoc_insertion_point(class_scope:cabane.io.BuzzResponse)
  ))
_sym_db.RegisterMessage(BuzzResponse)



_BUZZ = _descriptor.ServiceDescriptor(
  name='Buzz',
  full_name='cabane.io.Buzz',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=88,
  serialized_end=148,
  methods=[
  _descriptor.MethodDescriptor(
    name='Ask',
    full_name='cabane.io.Buzz.Ask',
    index=0,
    containing_service=None,
    input_type=_BUZZQUERY,
    output_type=_BUZZRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BUZZ)

DESCRIPTOR.services_by_name['Buzz'] = _BUZZ

# @@protoc_insertion_point(module_scope)
