# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: fizzer.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import cabane_io.fizzer_pb2 as fizzer_pb2


class FizzBase(abc.ABC):
    @abc.abstractmethod
    async def Ask(
            self, stream:
            'grpclib.server.Stream[fizzer_pb2.FizzQuery, fizzer_pb2.FizzResponse]'
    ) -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/cabane.io.Fizz/Ask':
            grpclib.const.Handler(
                self.Ask,
                grpclib.const.Cardinality.UNARY_UNARY,
                fizzer_pb2.FizzQuery,
                fizzer_pb2.FizzResponse,
            ),
        }


class FizzStub:
    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.Ask = grpclib.client.UnaryUnaryMethod(
            channel,
            '/cabane.io.Fizz/Ask',
            fizzer_pb2.FizzQuery,
            fizzer_pb2.FizzResponse,
        )
