# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fizzer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fizzer.proto',
  package='cabane.io',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0c\x66izzer.proto\x12\tcabane.io\"\x1b\n\tFizzQuery\x12\x0e\n\x06number\x18\x01 \x01(\x03\"\x1e\n\x0c\x46izzResponse\x12\x0e\n\x06isFizz\x18\x01 \x01(\x08\x32<\n\x04\x46izz\x12\x34\n\x03\x41sk\x12\x14.cabane.io.FizzQuery\x1a\x17.cabane.io.FizzResponseb\x06proto3')
)




_FIZZQUERY = _descriptor.Descriptor(
  name='FizzQuery',
  full_name='cabane.io.FizzQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='cabane.io.FizzQuery.number', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=54,
)


_FIZZRESPONSE = _descriptor.Descriptor(
  name='FizzResponse',
  full_name='cabane.io.FizzResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='isFizz', full_name='cabane.io.FizzResponse.isFizz', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=86,
)

DESCRIPTOR.message_types_by_name['FizzQuery'] = _FIZZQUERY
DESCRIPTOR.message_types_by_name['FizzResponse'] = _FIZZRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FizzQuery = _reflection.GeneratedProtocolMessageType('FizzQuery', (_message.Message,), dict(
  DESCRIPTOR = _FIZZQUERY,
  __module__ = 'fizzer_pb2'
  # @@protoc_insertion_point(class_scope:cabane.io.FizzQuery)
  ))
_sym_db.RegisterMessage(FizzQuery)

FizzResponse = _reflection.GeneratedProtocolMessageType('FizzResponse', (_message.Message,), dict(
  DESCRIPTOR = _FIZZRESPONSE,
  __module__ = 'fizzer_pb2'
  # @@protoc_insertion_point(class_scope:cabane.io.FizzResponse)
  ))
_sym_db.RegisterMessage(FizzResponse)



_FIZZ = _descriptor.ServiceDescriptor(
  name='Fizz',
  full_name='cabane.io.Fizz',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=88,
  serialized_end=148,
  methods=[
  _descriptor.MethodDescriptor(
    name='Ask',
    full_name='cabane.io.Fizz.Ask',
    index=0,
    containing_service=None,
    input_type=_FIZZQUERY,
    output_type=_FIZZRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FIZZ)

DESCRIPTOR.services_by_name['Fizz'] = _FIZZ

# @@protoc_insertion_point(module_scope)
