# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reducer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='reducer.proto',
  package='cabane.io',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rreducer.proto\x12\tcabane.io\"\x1d\n\x0bReduceQuery\x12\x0e\n\x06number\x18\x01 \x01(\x03\"\x1f\n\x0cReduceResult\x12\x0f\n\x07message\x18\x01 \x01(\t2A\n\x07Reducer\x12\x36\n\x03\x41sk\x12\x16.cabane.io.ReduceQuery\x1a\x17.cabane.io.ReduceResultb\x06proto3')
)




_REDUCEQUERY = _descriptor.Descriptor(
  name='ReduceQuery',
  full_name='cabane.io.ReduceQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='cabane.io.ReduceQuery.number', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=57,
)


_REDUCERESULT = _descriptor.Descriptor(
  name='ReduceResult',
  full_name='cabane.io.ReduceResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='cabane.io.ReduceResult.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=90,
)

DESCRIPTOR.message_types_by_name['ReduceQuery'] = _REDUCEQUERY
DESCRIPTOR.message_types_by_name['ReduceResult'] = _REDUCERESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReduceQuery = _reflection.GeneratedProtocolMessageType('ReduceQuery', (_message.Message,), dict(
  DESCRIPTOR = _REDUCEQUERY,
  __module__ = 'reducer_pb2'
  # @@protoc_insertion_point(class_scope:cabane.io.ReduceQuery)
  ))
_sym_db.RegisterMessage(ReduceQuery)

ReduceResult = _reflection.GeneratedProtocolMessageType('ReduceResult', (_message.Message,), dict(
  DESCRIPTOR = _REDUCERESULT,
  __module__ = 'reducer_pb2'
  # @@protoc_insertion_point(class_scope:cabane.io.ReduceResult)
  ))
_sym_db.RegisterMessage(ReduceResult)



_REDUCER = _descriptor.ServiceDescriptor(
  name='Reducer',
  full_name='cabane.io.Reducer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=92,
  serialized_end=157,
  methods=[
  _descriptor.MethodDescriptor(
    name='Ask',
    full_name='cabane.io.Reducer.Ask',
    index=0,
    containing_service=None,
    input_type=_REDUCEQUERY,
    output_type=_REDUCERESULT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_REDUCER)

DESCRIPTOR.services_by_name['Reducer'] = _REDUCER

# @@protoc_insertion_point(module_scope)
