# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: reducer.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import cabane_io.reducer_pb2 as reducer_pb2


class ReducerBase(abc.ABC):
    @abc.abstractmethod
    async def Ask(
            self, stream:
            'grpclib.server.Stream[reducer_pb2.ReduceQuery, reducer_pb2.ReduceResult]'
    ) -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/cabane.io.Reducer/Ask':
            grpclib.const.Handler(
                self.Ask,
                grpclib.const.Cardinality.UNARY_UNARY,
                reducer_pb2.ReduceQuery,
                reducer_pb2.ReduceResult,
            ),
        }


class ReducerStub:
    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.Ask = grpclib.client.UnaryUnaryMethod(
            channel,
            '/cabane.io.Reducer/Ask',
            reducer_pb2.ReduceQuery,
            reducer_pb2.ReduceResult,
        )
